[package]
version = "0.2.0"
name = "lofigirl_web_client"
description = "App Description"
categories = ["category"]
readme = "./README.md"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
seed = "0.8"
lofigirl_shared_common = { path = "../lofigirl_shared_common"}

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
