[workspace]
members = [
    "lofigirl_client", 
    "lofigirl_frontend",
    "lofigirl_server",
    "lofigirl_shared_common",
    "lofigirl_shared_listen",
    "lofigirl_sys", 
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
