[package]
name = "lofigirl"
version = "0.1.1"
authors = ["Gokberk Kocak <gokberkkocak@gmail.com>"]
edition = "2018"

[dependencies]
lofigirl_sys = { path = "../lofigirl_sys", optional = true }
lofigirl_shared = { path = "../lofigirl_shared"}
lofigirl_listen = { path = "../lofigirl_listen"}
reqwest = "0.11"
serde_json = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1.5", features = ["rt", "time"] }
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
url = { version = "2.2", optional = true}


[features]
standalone = ["lofigirl_sys", "url"]