[package]
name = "lofigirl_sys"
version = "0.1.0"
authors = ["Gokberk Kocak <gokberkkocak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lofigirl_shared = { path = "../lofigirl_shared"}
opencv = { version = "0.53", features = ["clang-runtime"]}
leptess = "0.13"
anyhow = "1.0"
thiserror = "1.0"
rustube = "0.2"
url = "2.2"